# Generated by Django 5.2 on 2025-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
